hellolf: hellolf.o
	gcc -o hellolf -Wall -pedantic hellolf.o
hellolf.o: hellolf.c
	gcc -c -Wall -pedantic hellolf.c
hellosc: hellosc.o
	gcc -o hellosc -Wall -pedantic hellosc.o
hellosc.o: hellosc.c
	gcc -c -Wall -pedantic hellosc.c
clean:
	rm hellolf hellolf.o hellosc hellosc.o