stdoutredir: stdoutredir.o
	gcc -o stdoutredir -Wall -pedantic stdoutredir.o
stdoutredir.o: stdoutredir.c
	gcc -c -Wall -pedantic stdoutredir.c
stdinredir: stdinredir.o
	gcc -o stdinredir -Wall -pedantic stdinredir.o
stdinredir.o: stdinredir.c
	gcc -c -Wall -pedantic stdinredir.c
clean:
	rm stdoutredir stdoutredir.o stdinredir stdinredir.o